### ISSUE TITLE
Core fn: nthrest

### ISSUE THREAD

**Issue by borkdude** [squint-cljs/squint#207]

**Comment by bhlieberman** [comment]
Pretty new to Clojure and OSS contributions but I was looking over the closed issue on seqs and iterators. This implementation seems entirely too naive and I'm happy to throw it away and start over but I figured I'd ask: anything immediately wrong with this? ```javascript
export function nthrest(coll, n) {
... return coll.slice(n);
... }```

**Comment by borkdude** [comment]
@bhlieberman The idea of these seq-like functions is that they are lazy. Laziness in ClavaScript is implemented using `LazyIterable` which takes a function which typically uses JS generators.

Your proposed impl only works for arrays, but not for e.g. `(range 10)`. Take a look at `drop`. In fact, I think `nthrest` is pretty similar to `drop`, so maybe we could just defer to `drop` in the implementation of `nthrest`, unless I'm missing something.

cc @lilactown @corasaurus-hex

**Comment by lilactown** [comment]
Yeah I think the difference is that `nthrest` (and `nthnext`) eagerly drop everything at the front, whereas `drop` waits until consumed before iterating over the dropped items.

I'm actually not sure off hand how to do this. Because iterators are mutable, and iterables are immutable, you can't easily consume the head of one and then cache it for later. For example, our implementation of `rest` lazily consumes the head and then continues iteration vs. the way that Clojure does it, where it eagerly consumes the head and creates a new seq from the tail.

**Comment by borkdude** [comment]
I'd say the behavior is close enough. I've personally never reached for `nthrest` and `nthnext` in CLJS and always used `take` and `drop`. Maybe we should just close this?

**Comment by borkdude** [comment]
Won't implement since there isn't any advantage compared to drop
