### ISSUE TITLE
with-out-str

### ISSUE THREAD

**Issue by corasaurus-hex** [squint-cljs/squint#31]
Is this something we want to add? If we do want to add this then we should probably do this before we do pr/prn, right?

**Comment by borkdude** [comment]
`prn` and `pr-str` are already there: they use `JSON.stringify`.

**Comment by corasaurus-hex** [comment]
Oh jeeze I just assumed. 🤦‍♀️

**Comment by borkdude** [comment]
I consider `prn` in squint totally broken since it relies in JSON.stringify which ignores a lot of stuff when it's not representable as JSON. I might want to switch to another implementation later which prints EDN-like stuff which can be copy-pasted back into the code. This will be a breaking change. I'll revisit with-out-str after that.
