### ISSUE TITLE
REPL fails with `(extends class-1)` in defclass

### ISSUE THREAD

**Issue by borkdude** [squint-cljs/squint#526]
Got it, so it fails with `(extends class-1)` in the REPL

_Originally posted by @borkdude in https://github.com/squint-cljs/squint/issues/517#issuecomment-2093171698_

**Comment by borkdude** [comment]
I opened a new issue here @tecumsehcommunications

**Comment by tecumsehcommunications** [comment]
It looks like this is more than one issue.

1) If you start with the example code given for classes and just compile it
gives no error.  But when you run it:

$ node sandbox2.mjs

export { class-1, Class2, c }
              ^
SyntaxError: Unexpected token '-'


Node does not like the hyphen in the class name.  I guess you change how
the parser handles this or change the code on the website.

2) After removing the hyphen and recompiling, running it now gives:

$ node sandbox2.mjs

super((x) + (y) + (self__._y));const self__ = this;
                   ^
ReferenceError: Cannot access 'self__' before initialization


3) I don't know if this is a related or a separate issue, but if you try
this from a repl, you can't get it to work because class definitions, when
sent to the repl to evaluate, do not set a symbol in the repl environment:

 user=> (defclass class1
  (field -x)
  (field -y :dude) ;; default
  (constructor [this x] (set! -x x)))
[class class1]

user=> class1
class1
ReferenceError: class1 is not defined

**Comment by borkdude** [comment]
Avoid the hyphens for now the, it's a munging issue.

**Comment by borkdude** [comment]
I fixed the `export { class-1, Class2, c }` problem.
I kind of lost track of what is the next problem. Can you maybe create a little example (preferably in the playground) to show what the next issue is?

**Comment by tecumsehcommunications** [comment]
I did just did a fresh pull from github. All of the examples I've submitted
are done in the playground.  The test code I am using is from
https://github.com/squint-cljs/squint/blob/main/doc/defclass.md without
modification. Here it is for your reference:

(defclass class-1
  (field -x)
  (field -y :dude) ;; default
  (^:static field a)
  (^:static field b :dude) ;; default
  (constructor [this x] (set! -x x))

  Object
  (get-name-separator [_] (str "-" -x))
  (^:static static-method [_] (str "static field: " a)))

(defclass Class2
  (extends class-1)
  (field -y 1)
  (constructor [_ x y]
               (super (+ x y -y)))

  Object
  (dude [_]
        (str -y (super.get-name-separator)))
  (^:async fetch [_]
    (js/fetch "https://clojure.org"))

  (toString [this] (str "<<<<" (.dude this) ">>>>") ))

(def c (new Class2 1 2))



 Here is the screen log of what I get when I try this code in the
playground:
================================

$ ~/lib/squint/playground$ squint compile test.cljs   <== this is the file
containing the above code
     [squint] Compiling CLJS file: test.cljs
     [squint] Wrote file:
/home/ubuntu/lib/squint/playground/public/js/test.mjs

$ ~/lib/squint/playground$ squint run test.cljs
     [squint] Running test.cljs
     file:///home/ubuntu/lib/squint/playground/public/js/test.mjs:36
export { class-1, Class2, c }
              ^

SyntaxError: Unexpected token '-'
    at compileSourceTextModule (node:internal/modules/esm/utils:337:16)
    at ModuleLoader.moduleStrategy
(node:internal/modules/esm/translators:166:18)
    at callTranslator (node:internal/modules/esm/loader:416:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:422:30)
    at async link (node:internal/modules/esm/module_job:88:21)

Node.js v22.0.0

===============================================

Now I take out the hyphens where class-1 is defined and referenced.  So now
it is "class1".  Otherwise, the code is the same. The screen log is:

==============================================

$ ~/lib/squint/playground$ squint compile test.cljs
[squint] Compiling CLJS file: test.cljs
[squint] Wrote file: /home/ubuntu/lib/squint/playground/public/js/test.mjs

$ ~/lib/squint/playground$ squint run test.cljs
[squint] Running test.cljs
file:///home/ubuntu/lib/squint/playground/public/js/test.mjs:19
super((x) + (y) + (self__._y));const self__ = this;
                   ^

ReferenceError: Cannot access 'self__' before initialization
    at new Class2
(file:///home/ubuntu/lib/squint/playground/public/js/test.mjs:19:20)
    at file:///home/ubuntu/lib/squint/playground/public/js/test.mjs:34:9
    at ModuleJob.run (node:internal/modules/esm/module_job:235:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:461:24)

Node.js v22.0.0
===========================================================

In contrast, running the code in the playground repl won't work either
because your can't reference the class even though you define it:

=========================================================

user => (defclass class1
  (field -x)
  (field -y :dude) ;; default
  (^:static field a)
  (^:static field b :dude) ;; default
  (constructor [this x] (set! -x x))

  Object
  (get-name-separator [_] (str "-" -x))
  (^:static static-method [_] (str "static field: " a)))

(defclass Class2
  (extends class1)
  (field -y 1)
  (constructor [_ x y]
               (super (+ x y -y)))

  Object
  (dude [_]
        (str -y (super.get-name-separator)))
  (^:async fetch [_]
    (js/fetch "https://clojure.org"))

  (toString [this] (str "<<<<" (.dude this) ">>>>") ))

user=> [class class1]
ReferenceError: class1 is not defined
    at eval (eval at Tha
(file:///home/ubuntu/.nvm/versions/node/v22.0.0/lib/node_modules/squint-cljs/lib/cli.js:29:46),
<anonymous>:4:22)
    at process.processTicksAndRejections
(node:internal/process/task_queues:95:5)
user=>Class2
Class2
ReferenceError: Class2 is not defined
    at eval (eval at Tha
(file:///home/ubuntu/.nvm/versions/node/v22.0.0/lib/node_modules/squint-cljs/lib/cli.js:29:46),
<anonymous>:4:1)
    at process.processTicksAndRejections
(node:internal/process/task_queues:95:5)
user=>

**Comment by borkdude** [comment]
With the playground I mean:

https://squint-cljs.github.io/squint/

If you hit the share button, you can share the example here via a link. But I'll try the code.

**Comment by borkdude** [comment]
I can reproduce the error `Cannot access 'self__' before initialization` here:

https://squint-cljs.github.io/squint/?src=KGRlZmNsYXNzIGNsYXNzLTEKICAoZmllbGQgLXgpCiAgKGZpZWxkIC15IDpkdWRlKSA7OyBkZWZhdWx0CiAgKF46c3RhdGljIGZpZWxkIGEpCiAgKF46c3RhdGljIGZpZWxkIGIgOmR1ZGUpIDs7IGRlZmF1bHQKICAoY29uc3RydWN0b3IgW3RoaXMgeF0gKHNldCEgLXggeCkpCgogIE9iamVjdAogIChnZXQtbmFtZS1zZXBhcmF0b3IgW19dIChzdHIgIi0iIC14KSkKICAoXjpzdGF0aWMgc3RhdGljLW1ldGhvZCBbX10gKHN0ciAic3RhdGljIGZpZWxkOiAiIGEpKSkKCihkZWZjbGFzcyBDbGFzczIKICAoZXh0ZW5kcyBjbGFzcy0xKQogIChmaWVsZCAteSAxKQogIChjb25zdHJ1Y3RvciBbXyB4IHldCiAgICAgICAgICAgICAgIChzdXBlciAoKyB4IHkgLXkpKSkKCiAgT2JqZWN0CiAgKGR1ZGUgW19dCiAgICAgICAgKHN0ciAteSAoc3VwZXIuZ2V0LW5hbWUtc2VwYXJhdG9yKSkpCiAgKF46YXN5bmMgZmV0Y2ggW19dCiAgICAoanMvZmV0Y2ggImh0dHBzOi8vY2xvanVyZS5vcmciKSkKCiAgKHRvU3RyaW5nIFt0aGlzXSAoc3RyICI8PDw8IiAoLmR1ZGUgdGhpcykgIj4%2BPj4iKSApKQoKKGRlZiBjIChuZXcgQ2xhc3MyIDEgMikp&repl=true

This is because a field name is used in a call to `super`. You're not allowed to do this, since the field isn't initialized at that point.
This would be similar as writing `super(x + y + this._y);`. Node.js will spit out an error for this:

ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor

The rest of the errors have been fixed, as you can verify on the playground (again: with playground I mean the website linked above, not the REPL). If you can provide a repro using the playground by hitting Share and pasting the link here, I'll happily look at this again. I will publish a new version of squint later today. 

Thanks!

**Comment by borkdude** [comment]
Ah now I get what you are saying, the docs contain that mistake, makes sense. I'll fix that and then release another squint.

**Comment by borkdude** [comment]
Done and published. Please let me know if you have any other problems.
